name: smartcare
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'  # Update this line

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0 # Add this line for flutter_signin_button
  shared_preferences: ^2.0.12 # Add this line for shared_preferences
  flutter_local_notifications: ^14.0.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - asset/images/splash.png
    - asset/images/Amber-R.jpg



